### ISSUE TITLE
maintenance check in index.php

### ISSUE THREAD

**Issue by web-media** [navjottomer/Osclass#154]
We should remove  maintenance check from index file . At this point  all osclass files are loaded . Plugins also. 
A  maintenance plugin can do same job if activated  , no need to check maintenance on each request .
Also drop  user session before  maintenance is a better way to handle this.

**Comment by navjottomer** [comment]
Maintenance check is needed to show frontend visitors that site is under maintenance, I don't see any harm in it. 
It also provide a method for theme developers to customise maintenance appearance.
The site may be in maintenance mode but admin can access the site and that's why plugins and osclass core should be loaded.
