### ISSUE TITLE
Using this fork on a production site

### ISSUE THREAD

**Issue by webmods-croatia** [navjottomer/Osclass#61]
Are there any known big problems/issues/bugs that would stop me from trying to use this on a production site?

I need to upgrade from 3.7.4 anyways...

**Comment by dimalif** [comment]
If you feel adventurous, yes use it. First do a normal update to stock 3.8 and THEN upload this fork.

Still, your question (and other's question from what i see at the forums of Osclass) brings an other matter. A Roadmap of this fork/project. What is the roadmap and the goal ?

**Comment by webmods-croatia** [comment]
> First do a normal update to stock 3.8 and THEN upload this fork.

Ok.

I think it would be useful if someone would use this on a live, production site and post issues they found. I think I'll do it...



> What is the roadmap and the goal ?

> Transform osclass to adapt new features, get rid of deprecated code. And set the road for new goals.

Which new goals? I don't know, yet.

**Comment by dimalif** [comment]
I mean ... there will be a release or something at some point ?

**Comment by webmods-croatia** [comment]
> I mean ... there will be a release or something at some point ?

@navjottomer 

Osclass 3.8.0 installed successfully, my mods replicated and everything works perfectly.
Tomorrow going to try this fork out.

P.S. what is the last stable version of PHP I can use? With 3.7.4 I was running PHP 5.6.

**Comment by dimalif** [comment]
In General

Latest stable: 7.1.32 or 7.3.9 

__

For Osclass i would say 7.1.x.

**Comment by webmods-croatia** [comment]
> In General
> 
> Latest stable: 7.1.32 upto 7.3.9
> 
> __
> 
> For Osclass i would say 7.1.x.

With 7.1 and 7.2 I always get "reCAPTCHA" wrong on the register page. It happened with 3.7.4 as well.

**Comment by dimalif** [comment]
You gonna use the master or develop of this fork to the live site ?

**Comment by webmods-croatia** [comment]
> You gonna use the master or develop of this fork to the live site ?

Master on live site. I will test develop locally.

**Comment by navjottomer** [comment]
I wouldn't recommend any branch on live site. They are not tested that much, though I'll not stop anyone if they know what they are doing.

**Comment by navjottomer** [comment]
> If you feel adventurous, yes use it. First do a normal update to stock 3.8 and THEN upload this fork.
> 
> Still, your question (and other's question from what i see at the forums of Osclass) brings an other matter. A Roadmap of this fork/project. What is the roadmap and the goal ?

A roadmap of this project initially was to create a separate build for my site and my clients, with few or more essential modifications. 
Then I thought it would be better to involve the community and pass on any good to osclass original repo back if it is really useful. 
No one gets really involved and the project was stalled and I also found that new osclass devs do not want anyone to create an alternative because that may hurt original osclass. 
Respecting that I stopped updating github repo and keep my private repo private for personal use and for clients.
After the announcement that osclass market is closing down and when someone asked me to post about this repo in osclass forum, I made it a go again.
NOW:
Currently, I am only interested to make this build refined and bug-free. Future is not decided because osclass is still alive and don't get me wrong but sometimes they seems more closed than most closed-source projects and I do not know what reaction they will have for this repo if it will try to be an alternative of original osclass.
I will not create an alternative if they actively develop osclass after official market shutdown. They are a big team and I am no alternative to their workforce and I really don't want to waste my effort for no reason.

**Comment by dimalif** [comment]
Sorry but "big teams"they  SPEAK UP and do not keep in silence like that. 

Also "actively develop osclass" ? Do they keep us in mystery, so we are all delitefully surprised ?

C'on ......

**Comment by navjottomer** [comment]
I meant if they do not develop in secrecy as they did with last osclass update.

**Comment by webmods-croatia** [comment]
> I meant if they do not develop in secrecy as they did with last osclass update

I wouldn't bet on that. Market was their only source of revenue and it made them work on Osclass more. Now that they won't earn anything, I don't think they'll work on Osclass.

Also, if you visit GitHub or Twitter profiles of (ex) Osclass Team members, you can see they work on other projects.

**Comment by navjottomer** [comment]
If they will not then we will. 
BTW we should not discuss this non-development related things on GitHub. It would be better if someone set up this https://github.com/discourse/discourse so we can have an open place which really meant for discussion.
I can also do that but I don't have that much time because I have some personal issues right now.

**Comment by dimalif** [comment]
Well, what i do understand is that the only thing some one should do is actually find a way to remove any dependancy from the Market, geo, updates, or whatever other is in there that connects with osclass.org.

Nothing else. Not this fork, not an other fork, nothing. From what i understand (after seeing a lot of situations like this in Wordpress plugins, and i mean a lot), this fork will end in nothing. At some point it will be abandoned...

And also look for an alternative, Osclass 3.8 won't last long, 1-2 years or so.

**Comment by webmods-croatia** [comment]
> Well, what i do understand is that the only thing some one should do is actually find a way to remove any dependancy from the Market, geo, updates, or whatever other is in there that connects with osclass.org.
> 
> Nothing else. Not this fork, not an other fork, nothing. From what i understand (after seeing a lot of situations like this in Wordpress plugins, and i mean a lot), this fork will end in nothing. At some point it will be abandoned...
> 
> And also look for an alternative, Osclass 3.8 won't last long, 1-2 years or so.

Here you have the guide I have written today on removing connections with Market on existing Osclass installations. https://docs.osclasscommunity.com/removing-market/

I didn't touch locations as they still work...

That changes are added in my pull request as well.

**Comment by dimalif** [comment]
@webmods-croatia Thanks a million times, excellent guide.

**Comment by webmods-croatia** [comment]
> I wouldn't recommend any branch on live site. They are not tested that much, though I'll not stop anyone if they know what they are doing.

I think I'll do some basic test locally and then try it live.

> It would be better if someone set up this https://github.com/discourse/discourse

Is there any PHP alternative you suggest? I can install Ruby, but PHP would be easier...

> @webmods-croatia Thanks a million times, excellent guide.

You're welcome! :)

**Comment by webmods-croatia** [comment]
> It would be better if someone set up this https://github.com/discourse/discourse

> Is there any PHP alternative you suggest? I can install Ruby, but PHP would be easier...

Or to make things simpler, use good old SMF? forums.osclasscommunity.com.

**Comment by navjottomer** [comment]
forums.osclasscommunity.com is good too. Can I update it in ReadMet?

**Comment by webmods-croatia** [comment]
> forums.osclasscommunity.com is good too. Can I update it in ReadMe?

Sure. :) @fre2mansur

**Comment by webmods-croatia** [comment]
@dimalif I added another page on the guide, not a mandatory mod but it helps... https://docs.osclasscommunity.com/removing-market/remove-calls-to-osclass/disable-upgrade-page

**Comment by webmods-croatia** [comment]
The market is up and running. What are you doing, Osclass?

**Comment by navjottomer** [comment]
Discussion is moved here. Closing it now, only open if necessary.
https://osclass.discourse.group/t/using-this-fork-on-a-production-site/28
